penumbra-zone/dex-explorer

- README.md
Cleans up inactive URLs, adds some general advice on hosting, and links out to relevant docs. Follow-up to changes in [0].
[0] https://github.com/penumbra-zone/dex-explorer/pull/26
> docs: update deployment references

- Containerfile
The current build is failing because it expects a package lock file that doesn't exist.
Updating the dockerfile to use pnpm here.
> Update dockerfile to use pnpm

- Containerfile
Current build breaks as the previous step uses pnpm build whereas in the next image it uses npm run build.
> Update dockerfile as next image

- package.json
- pnpm-lock.yaml
- src/components/charts/ohlcChart.tsx
Fixes the issue that the chart doesnt span the full width:
> Set Chart to full width

- README.md
- justfile
- src/utils/indexer/connector.tsx
Adds opt-in support for declaring a CA certificate value for the database TLS connection. Some managed postgres solutions, such as DigitalOcean's, require this setting. In order to use it:
1. set the PENUMBRA_INDEXER_CA_CERT env var with the string contents of the db's CA
2. remove the `sslmode=require` from the connection auth string
The need for 2 is because the `connectionString` param clobbers any manual `ssl` opts in the db config, and is documented here [0].
Closes #55.
[0] https://node-postgres.com/features/ssl#usage-with-connectionstring
> feat: support PENUMBRA_INDEXER_CA_CERT env var override

- package.json
- pnpm-lock.yaml
> chore: bump registry to v11.3.1

- .gitignore
- README.md
- flake.lock
- flake.nix
- justfile
Adds a nix config so that tooling like `pnpm` is available immediately. Fleshes out the documentation around connecting to managed database instances, since merge of #56.
> docs: add quickstart docs for dev env

- src/app/v2/explore/page.tsx
- src/app/v2/inspect/page.tsx
- src/app/v2/page.tsx
- src/app/v2/portfolio/page.tsx
- src/app/v2/trade/page.tsx
- src/pages/index.tsx
- src/utils/routes/pages.ts
As title says, this PR adds the pages for the v2 routes.
> Setup pages for v2 routes

- next.config.mjs
- package.json
- pnpm-lock.yaml
- src/app/StyleRegistry.tsx
- src/app/layout.tsx
Fixes #87 
Solves the issue with FOUC in server-side environment.
Tried creating the same `StyledComponentsRegistry` component in the UI package but apparently it cannot be used in NextJS after the Vite's build. That's why the whole piece of code is put here. However, we should document this in the UI package docs for the future.
> fix: #87: support styled-components in SSR to solve FOUC

- .github/workflows/deploy.yml
- flake.lock
- flake.nix
Now that we've resolved #73, we're unblocked from restoring rolling deployments on merge to main, to the testnet instance [0]. This new workflow blocks on completion of the build-container logic, then bounces the pre-existing deployment to pull the most recently built container.
Refs #72.
[0] https://dex-explorer.testnet.plinfra.net
> ci: add automatic deploys to testnet environment

- .github/workflows/container.yml
- .github/workflows/deploy.yml
Since the deploy workflow depends on the container workflow, we'll trigger the latter on running the former. Therefore the container workflow shouldn't run on its on when main changes.
Also cleans up the post-deploy wait-for task to use proper shell commands.
Follow-up to https://github.com/penumbra-zone/dex-explorer/pull/90. Refs #72.
> ci: only build container once per merge

- next.config.mjs
- package.json
- pnpm-lock.yaml
- scripts/add-tgz.ts
Fixes https://github.com/penumbra-zone/dex-explorer/issues/115
Depends on https://github.com/penumbra-zone/web/pull/1883
Implements the same process of installing local dependencies as in the Prax repo:
1. In Web, do `pnpm dev:pack`. This would run the build of all packages and, after the build, prepare tarballs (`.tgz` files). Don't stop this command to continue watching for changes.
2. In Dex-explorer, run `pnpm add:tgz PATH_TO_WEB_REPO/packages/*/*.tgz` to install the package tarballs locally
3. In Dex-explorer, run `pnpm dev:local` to configure Webpack to watch for the package changes, re-run `pnpm install` and clear webpack's cache.
Notice: the `pnpm dev:local` currently has the undiagnosed issue of re-running `pnpm install` for too many times. For me, it took 3 minutes to set up the …
> feat: add scripts and webpack plugins to watch for local package changes

- .dockerignore
- .gitignore
- Containerfile
- justfile
We noticed a regression between v1 and v2 versions in the built container. In the local dev env, created via `pnpm run dev`, v2 served just fine, but the container uses `pnpm run build` output for a prod site, and that site works differently.
Small changes throughout:
* updated justfile targets to facilitate local testing of containers
* refreshed dockerignore file for faster local container builds
* migrated use of `npm` in container build to `pnpm` for consistency
These are all good changes but we still don't have a fully working v2 site served via container.
> build: update container image context

- app/api/env/route.ts
Possibly closes https://github.com/penumbra-zone/dex-explorer/issues/121
By default, the `api/env` route was being built statically at build time. It looks like Nextjs recognized that it depended on static variables (env vars) and thought it a good idea to pre-build the route's response #facepalm. 
Before:
After:
> Make env route dynamic

- package.json
- pnpm-lock.yaml
- src/pages/trade/model/trace.test.ts
- src/pages/trade/model/trace.ts
- src/pages/trade/ui/route-book.tsx
- src/pages/trade/ui/trade-row.tsx
- tailwind.config.ts
> feat: mobile view of route book

- .github/workflows/deploy.yml
Deploys another instance of the dex-explorer, also on merges into main branch. This new logic is straightforward, but won't run until merge: that's fine, I'll follow-up post-merge and make sure it's working correctly.
> ci: add another deploy workflow

- src/pages/trade/api/candles.tsx
- src/shared/api/server/candles/index.ts
- src/shared/api/server/candles/types.ts
- src/shared/api/server/candles/utils.ts
- src/shared/database/index.ts
- src/shared/utils/duration.ts
Closes https://github.com/penumbra-zone/dex-explorer/issues/148
Closes https://github.com/penumbra-zone/dex-explorer/issues/151
This changes the logic to rely on the database to integrate price information for both directions, which simplifies the logic on our end, and makes us correctly integrate tweaks to this logic without needing changes.
This also fills empty candles in between the start and end dates of the candles provided by the database.
> candles: rely on database for symmetrization, fill empty candles

- src/shared/utils/serializer.ts
Recently the pindexer started saving/returning dates as date-objects, not as strings, therefore breaking the serialization. This fix restores the explore page affected by the change
> fix: serialize dates too

- src/pages/inspect/ui/actions.tsx
- src/pages/inspect/ui/executions.tsx
- src/pages/inspect/ui/result.tsx
- src/pages/inspect/ui/volume.tsx
- src/shared/api/server/position/timeline/state.ts
Fix data issues with LP inspect page and restore timeline layout.
The rendering still needs to restore the asset icons but this can be done later.
> LP inspect fixes

- src/pages/trade/ui/route-book.tsx
- src/pages/trade/ui/route-tabs.tsx
- src/pages/trade/ui/trade-row.tsx
fixes #146 
- Adjusted padding in routebook
- Replace custom skeleton with the reusable skeleton
- Adjusted formatting of numbers to conform with Figma and fit on smaller screens, including the padding.
> fix: routebook visual updates

- src/pages/inspect/lp/api/position.ts
- src/pages/inspect/lp/api/types.ts
- src/pages/inspect/ui/actions.tsx
- src/pages/inspect/ui/executions.tsx
- src/pages/inspect/ui/state-details.tsx
- src/pages/inspect/ui/volume.tsx
- src/pages/trade/ui/positions.tsx
- src/shared/api/server/position/timeline/executions.ts
- src/shared/api/server/position/timeline/index.ts
- src/shared/api/server/position/timeline/state.ts
- src/shared/api/server/position/timeline/types.ts
- src/shared/api/server/position/timeline/volume.ts
- src/shared/api/server/position/timeline/withdraws.ts
- src/shared/utils/serializer.ts
Follow up from: https://github.com/penumbra-zone/dex-explorer/pull/171
Does three things:
1 - Moves registry + ValueView assembly to react-query as it was a heavy load sending that info from server.
2 - Add symbol to icons in volume table
3 - Add link to inspect page from My Positions table
> Lp inspect: move registry info to frontend

- src/pages/trade/api/book.ts
- src/pages/trade/api/candles.tsx
- src/pages/trade/model/useSummary.ts
- src/shared/api/compact-block.ts
The `useRefetchOnNewBlock()` is overfetching as there isn't a cache for the many re-render calls happening. 
Before/after fix:
https://github.com/user-attachments/assets/29b4b3c4-157a-4f41-ab47-546598a16ca9
> Over-fetching hook

- src/shared/model/connection/index.ts
fixes #157 by reloading on wallet disconnect
> fix: reload on wallet disconnect

- src/features/connect/connect-button.tsx
- src/pages/trade/ui/chart.tsx
- src/pages/trade/ui/positions.tsx
- src/pages/trade/ui/summary.tsx
- src/shared/ui/blockchain-error.tsx
> feat: add new minimal connect button, connect wallet

- app/app.tsx
- src/pages/trade/model/AssetInfo.ts
- src/pages/trade/ui/order-form/order-form-market.tsx
- src/pages/trade/ui/order-form/order-input.tsx
- src/pages/trade/ui/order-form/store/MarketOrderFormStore.ts
- src/pages/trade/ui/order-form/store/calculate-price-impact.ts
- src/pages/trade/ui/order-form/store/estimate-amount.ts
- src/pages/trade/ui/order-form/store/types.ts
- src/shared/api/transport.ts
Closes #221 
Features:
1. Allow estimations without connecting a wallet
2. Fix the invertion of the price estimation
3. Calculate the price impact of a trade and display it in the UI
4. Display the unfilled amount estimation if there's any
> feat: #221: market order improvements

- app/api/recent-executions/route.ts
- src/pages/trade/api/recent-executions.ts
- src/pages/trade/ui/market-trades.tsx
- src/pages/trade/ui/trades-tabs.tsx
- src/shared/api/server/recent-executions.ts
- src/shared/database/index.ts
Populating view for:
Note, route data is not available in pindexer.
> Display recent executions

- src/pages/trade/model/positions.test.ts
- src/pages/trade/model/positions.ts
- src/pages/trade/ui/positions-current-value.tsx
- src/pages/trade/ui/positions.tsx
- src/shared/math/position.test.ts
- src/shared/math/position.ts
This PR:
- supersedes #235 
- rework the position rendering logic and fix a collection of issues with price calculations and exponent handling
- lays the groundwork for doing renders based on a "well-known numeraire" list
- fills the current value column with the current value of the portfolio
This is the byproduct of a pairing session and discussion with @JasonMHasperhoven. There are string of low hanging fruits that we can refactor. **We will do this later**. Next steps should be to:
- add a couple tests (scaffolding is setup)
- do basic end to end actions using the dex
- use this work as a stepping stone to ship a smooth range liquidity experience
> fix: rework position rendering logic

- src/pages/trade/ui/order-form/store/OrderFormStore.ts
- src/pages/trade/ui/pair-selector/search-results.tsx
- src/shared/api/balances.ts
Closes #250
- filters out lpNFTs and all other unswappable assets (votes, proposal nfts, auction nfts, delegations)
- shows balances per selected sub-account
- fixes the bug with non-unique keys in react map
> fix: #250: filter assets in pair selector correctly

- src/shared/api/server/summary/all.ts
- src/shared/api/server/summary/pairs.ts
- src/shared/api/server/summary/single.ts
- src/shared/utils/stables.ts
addresses feedback in https://github.com/penumbra-zone/dex-explorer/pull/223 + sorts pairs by decreasing liquidity
-----------------
> explore page: data rendering

- src/shared/model/status/index.ts
- src/widgets/header/ui/status-popover.tsx
Closes #245 
- Stopped displaying `undefined` in the status popover
- Added 'loading' state to the popover – before it was just opening a popover with 'Status' text and nothing else
> fix: #245: hide `undefined` in status popover

- src/pages/trade/ui/order-form/order-form-market.tsx
- src/pages/trade/ui/order-form/store/MarketOrderFormStore.ts
Closes #268 
- Disables the Slider if the balance of controlled asset is empty. Tried removing Slider but disabling is better UI
- For 'Sell' tab, uses base asset instead of quote asset
> fix: #268: disable slider for empty balances

- src/pages/trade/ui/order-form/store/OrderFormStore.ts
fixes https://github.com/penumbra-zone/dex-explorer/issues/243
properly [indexes](https://github.com/penumbra-zone/dex-explorer/blob/main/src/pages/trade/ui/order-form/store/OrderFormStore.ts#L249) the subAccounts array coming out of [useSubaccounts()](https://github.com/penumbra-zone/dex-explorer/blob/main/src/pages/trade/ui/order-form/store/OrderFormStore.ts#L268)
------------------
https://github.com/user-attachments/assets/cf6a80b6-e5b6-400f-8f6b-8fe3609c12ae
> subaccounts: fix subaccount mapping

- src/shared/api/transport.ts
- src/shared/model/connection/index.ts
Closes #158 
Using `alert` here instead of `openToast` because this check requires us to disconnect user from the DEX. Disconnect causes a page reload, so the tooltip won't persist.
> fix: #158: check if wallet is on wrong chain and disconnect

- src/pages/trade/model/use-path.ts
references https://github.com/penumbra-zone/dex-explorer/issues/284
Initially, I thought it was related to our custom server‐side middleware matching on `['/', '/trade']`, so any path like `/trade/btc/usdc` wouldn't get intercepted. Turns out simply normalizing the base and quote symbols by capitalizing them fixes the NextJS routing. 
-----------------
https://github.com/user-attachments/assets/e4dee549-cdb7-4b7e-83b9-bc395d77cd34
> url: fix search path

- package.json
- pnpm-lock.yaml
- scripts/generate-pindexer-schema.ts
- src/pages/trade/api/recent-executions.ts
- src/pages/trade/ui/market-trades.tsx
- src/pages/trade/ui/route-book/trade-row.tsx
- src/shared/api/server/recent-executions.ts
- src/shared/database/index.ts
- src/shared/database/schema.ts
This PR adds basic execution stream support, in particular it:
- updates the schema codegens to be compatible with the `dex_ex_batch_swap_traces` table
- rework the query transform combinator to render each trace cleanly
- makes two pindexer queries in each direction (base -> quote, and vice-versa), weaving the results together.
Working on a follow-up PR to make it a bit sleeker, compact and capture a sense of speed for the interface.
It would be good to transfer over the work done on the route book so that we can render each route when hovering on a cell in the recent trades list.
> explorer: basic execution stream support

- src/pages/portfolio/ui/assets-table.tsx
fixes #278 
this pr consumes the new registry and prefers the registry primaryColorHex, falling back to a generated random color if there is none (shouldn't happen, the registry update script auto-generates the colors on new assets).
> feat: prefer primary color hex

- src/pages/explore/ui/stats.tsx
- src/shared/api/server/stats.ts
- src/shared/api/server/summary/all.ts
- src/shared/api/server/summary/single.ts
- src/shared/api/server/summary/types.ts
- src/shared/database/index.ts
- src/shared/utils/serializer.ts
Closes #302.
Closes #300.
The aggregate information wasn't being pulled correctly, I refactored that substantially to simplify the logic.
I touched the summary logic much less, and the only incorrect thing was just not using the recently added pre-calculated USDC volume inside pindexer. Doing so corrects discrepancies between the aggregate view and the per-pair view.
There are still some latent issues stemming from the fact that pindexer assumes directed trading pairs, and this page de-duplicates to get an undirected pair, and so some numbers like volume and liquidity may be only "half" what they should, but that can be corrected later once we display, e.g. volume or liquidity with directions.
> Correct data extraction from pindexer for explore page

- src/shared/api/server/stats.ts
Is causes by incorrectly fetching the USDC metadata on the server. This fixes that to allow the explore aggregate stats to work again.
> bug: fix aggregate stats not displaying because of USDC

- src/pages/trade/model/positions.ts
This PR fix withdrawals of auto-closing positions (#241).
Unfortunately, the approach we workshopped in #282 does not work because the `PositionStore` is already given a list of positions directly fetched from the DEX RPC service (latest state). This was an oversight on my part.
The code is hacky, maybe one could say that it sucks (?), but it works and we should **spend no time** trying to make it structurally better. We can fix linting, but let's keep it minimal. Our attention should be directed to the opened TODOs.
> fix: we can withdraw auto-closing positions

- src/pages/explore/ui/stats.tsx
Previously, this was displaying the largest trading pair twice.
> bug: display correct pair for top price mover

- src/shared/api/server/summary/types.ts
- src/shared/utils/serializer.ts
This is a data issue in pindexer, but we should handle this in a robust way, instead of keeling over.
Closes #324.
> Stopgap: treat negative liquidity and volume as positive

- src/pages/trade/model/positions.ts
- src/pages/trade/ui/positions/index.tsx
Simply wrapping the positions calculation into try/catch block, so that it doesn't crash the app.
The crash can happen per-position if the asset is not matched in the registry – happened to me after creating position in `pcli` and checking it in the DEX.
> fix: positions crashing the app

- src/pages/trade/model/use-path.ts
- src/pages/trade/ui/pair-selector/search-results.tsx
- src/pages/trade/ui/pair-selector/selector.tsx
Closes #316 
General improvements to the PairSelector component:
1. Both base and quote assets are prefilled when opening the pair selector, so users won't have to reselect assets from scratch
2. When searching for an asset and selecting it, the main screen will now appear again with confirmation button
3. Scroll restores to the top after selecting assets, so users don't get confused
> fix: #316: improve pair selector UX

- Containerfile
The deploy pipeline was failing on container builds (across the PL frontend repos) due to upstream breakage in corepack [0]. This changes matches changes in e.g. [1].
[0] https://github.com/nodejs/corepack/issues/612
[1] https://github.com/penumbra-zone/penumbers/pull/19
> fix(build): ditch corepack in containerfile

- src/shared/api/server/summary/all.ts
follow up from https://github.com/penumbra-zone/dex-explorer/pull/254, we should instead sort pairs by direct volume rather than liquidity on the explore page
-----------
_before_
------------
_after_
> sorting by decreasing volume

- src/pages/explore/api/use-summaries.ts
- src/pages/explore/ui/pairs.tsx
- src/shared/api/server/summary/all.ts
- src/shared/database/index.ts
- src/shared/utils/use-debounce.ts
Perfecting the explore page:
1. Implement search feature – user enters the string value, frontend sends the request with 400ms debounce, backend computes AssetIds, Pindexer filters by this array
2. Move sorting logic to SQL completely, this unlocks correct pagination
3. Move filtering logic to SQL completely (by volume != 0 OR liquidity != 0)
4. Change inner join with candles table to the left join, so 5 more active assets are not filtered out
5. Display info if no pairs are found
https://github.com/user-attachments/assets/e2fef983-e203-4c4b-98eb-194c4a45fcb1
> feat: improve data requests for trading pairs

- src/pages/explore/ui/stats.tsx
A nonsensical value on the top of the first page that a user sees casts doubt on the entire render, so we are going to disable it until we fix it.
Before:
After:
> explore: disable top price mover until query is fixed

- src/shared/api/server/book/helpers.ts
- src/shared/api/server/book/index.ts
- src/shared/utils/value-view.ts
Closes #369.
However! Where there's smoke there's fire, and I think there's probably other places where we're doing the math wrong, given the tangle nest interactions of pnum, BigNumber, etc. Longer term we should probably have some kind of actual domain type for prices, with functions for the associated ability to apply prices to values, with a runtime check that the asset ids match, and defer rendering as late as possible, with a single source of truth for doing the correct tricky math around exponents when rendering a price.
Previously, the route book would return odd data, like infinities, or negative spreads:
I think the culprit here boils down to this part of the processing logic:
https://github.com/penumbra-zone/dex-explorer/blob/18fac1d01300c3a571f4aaea610cf013bc6fd2e5/src/shared/a …
> bug: calculate route book correctly

- src/entities/position/ui/error-notice.tsx
- src/entities/position/ui/table.tsx
- src/pages/portfolio/api/use-transactions.ts
- src/pages/portfolio/ui/position-tabs.tsx
- src/pages/portfolio/ui/transactions.tsx
- src/shared/utils/use-observer.ts
- src/shared/utils/use-throttle.ts
Closes #394 
Thanks to @TalDerei, the #394 issue made me reflect on the infinite scroll and generalize the `useObserver` hook.
PR contents:
- Fix to `useTransactions` hook – it was incorrectly limiting data before subaccount filtering
- Improve `useObserver` hook – it now uses throttled data fetcher, meaning that next page requests cannot fire more often than 400ms
- Remove the loader from transactions list – the request time is so fast that showing the loader only caused the fiickering
> fix: #394: transaction pagination history
