package.json, pnpm-lock.yaml
Closes https://github.com/penumbra-zone/dex-explorer/issues/57
=> Bump registry to 11.3

src/utils/indexer/connector.tsx
Add support to pass a path name as value for the env PENUMBRA_INDEXER_CA_CERT
=> Add path value support for env PENUMBRA_INDEXER_CA_CERT

src/app/v2/trade/page.tsx
https://github.com/user-attachments/assets/95848c6a-7b9b-49d7-89c3-72aeb4dfd8e0
=> Responsive trade layout

package.json, pnpm-lock.yaml
Relates to https://github.com/prax-wallet/registry/pull/108
Makes registry parsing of metadata to be forward compatible.
=> Update registry to latest

src/pages/trade/ui/summary.tsx, src/shared/api/server/summary.ts, src/shared/database/index.ts
Small follow ups from: https://github.com/penumbra-zone/dex-explorer/pull/135
=> Adjust db query for summaries

app/portfolio/page.ts, app/portfolio/page.tsx, package.json, pnpm-lock.yaml, src/pages/portfolio/index.tsx
=> feat: mobile view of portfolio page

src/pages/trade/api/candles.tsx
This is an addendum to #159, which I accidentally merged before including in this change, woops
=> Add helper function for empty candle insertion

src/shared/api/server/summary/types.ts
Closes https://github.com/penumbra-zone/dex-explorer/issues/176
Currently decimals are being returned and raising
=> Floor volume vals

.github/workflows/ci.yml, src/pages/explore/ui/preview-chart/preview-adapter.test.ts, src/pages/trade/api/candles.tsx, src/pages/trade/model/trace.test.ts, src/pages/trade/ui/chart.tsx, src/shared/api/server/candles/index.ts, src/shared/api/server/candles/utils.test.ts, src/shared/api/server/candles/utils.ts, vite.config.ts
Closes https://github.com/penumbra-zone/dex-explorer/issues/150
Closes https://github.com/penumbra-zone/dex-explorer/issues/174
A bit of a smorgasbord of bug fixes (sorry!). Main motivation was to fix the Chart rendering issue. But found a few 🐛 along the way.
=> Chart rendering bug fix

src/pages/inspect/lp/api/position.ts, src/pages/inspect/lp/api/types.ts, src/pages/inspect/ui/actions.tsx, src/pages/inspect/ui/state-details.tsx, src/shared/api/server/position/timeline/executions.ts, src/shared/api/server/position/timeline/state.ts, src/shared/api/server/position/timeline/types.ts, src/shared/api/server/position/timeline/volume.ts, src/shared/api/server/position/timeline/withdraws.ts
Bug fix. Currently intermingling openingReserves & currentReserves. Making them explicitly separate the displaying correctly now.
=> Fix opening reserve value

src/widgets/header/ui/banner.tsx, src/widgets/header/ui/header.tsx
banner on the top of the dex explorer that clarifies that it’s a pre-alpha development preview
=> ui: alpha dev banner

src/pages/trade/ui/chart.tsx, src/pages/trade/ui/form-tabs.tsx, src/pages/trade/ui/page.tsx, src/pages/trade/ui/route-book.tsx, src/pages/trade/ui/summary.tsx, src/widgets/header/ui/banner.tsx, src/widgets/header/ui/header.tsx, src/widgets/header/ui/subaccount-selector.tsx
Closes https://github.com/penumbra-zone/dex-explorer/issues/184
https://github.com/user-attachments/assets/aa2286fb-7708-42fb-a2a0-79230528dc0e
=> Page grid update

src/pages/trade/ui/order-form/store/index.ts
Currently throwing when wallet attempts to reconnect:
https://github.com/user-attachments/assets/8590e3b0-3a7a-465c-be10-7e35cedf6492
=> Order form bug fix

src/shared/api/server/candles/index.ts, src/shared/api/server/candles/utils.ts
Closes: https://github.com/penumbra-zone/dex-explorer/issues/169
Before:
After:
=> Normalize chart vals

app/layout.tsx, package.json, pnpm-lock.yaml
Given the privacy-orientation, don't see a reason to keep this.
=> Remove Analytics/Speed Insights

src/pages/trade/ui/order-form/order-form-market.tsx
fixes #196 
@TalDerei can you please clarify what you meant by your last point in the issue (misplaced elements leading to inconsistent visual alignment)?
=> fix: market buy and sell UI bugs

src/pages/trade/ui/order-form/store/OrderFormStore.ts, src/shared/utils/is-metadata-equal.ts
Closes #214 
Displays available balance based on the selected sub-account
=> fix: #214: use selected sub-account in order forms

src/pages/trade/ui/chart.tsx
Addresses https://github.com/penumbra-zone/dex-explorer/issues/172
=> Add time info to chart x axis

src/pages/portfolio/ui/assets-table.tsx
=> feat: better assets bar

src/pages/trade/ui/order-form/store/OrderFormStore.ts
=> fix: don't spam the user with gas estimation failed error toasts

src/pages/trade/model/positions.ts, src/pages/trade/ui/positions.tsx
Implements https://github.com/penumbra-zone/dex-explorer/issues/266
=> Update withdrawn amounts & prices to show dash

src/pages/trade/ui/order-form/info-row.tsx, src/pages/trade/ui/order-form/order-form-limit.tsx, src/pages/trade/ui/order-form/store/LimitOrderFormStore.ts
=> fix: #237: add available balance field to the limit order form

src/shared/api/server/book/helpers.ts, src/shared/api/server/book/index.ts, src/shared/api/server/book/types.ts
This fix #285, and simplifies the route book construction logic.
=> api(book): fix sell side calculation

src/shared/api/server/recent-executions.ts
Closes #303 
Made this mistake before because of lack of knowledge. Fixing now
=> fix: #303: hops

src/pages/trade/ui/positions/action-button.tsx, src/pages/trade/ui/positions/index.tsx
Fixes regression of https://github.com/penumbra-zone/dex-explorer/issues/266 and https://github.com/penumbra-zone/dex-explorer/pull/277
=> Fix withdrawn state

src/pages/trade/ui/order-form/order-form-limit.tsx
Implements https://github.com/penumbra-zone/dex-explorer/issues/269
=> Add receive/"pay with" info line to limit order form UI

src/pages/portfolio/ui/assets-table.tsx
=> feat: disable buy and sell buttons for assets table

src/pages/explore/ui/stats.tsx, src/pages/trade/model/positions.ts, src/shared/utils/is-symbol.ts
Implements https://github.com/penumbra-zone/dex-explorer/issues/279
=> Swap direction of volume pair if base is stable or important numeraire

src/pages/trade/ui/market-trades.tsx, src/shared/api/server/recent-executions.ts
Fixes https://github.com/penumbra-zone/dex-explorer/issues/321
Tested by pointing to mainnet:
UM/USDC:
OSMO/USDY
USDY/OSMO
=> Fix amount + price in market executions

src/shared/api/server/position/timeline/state.ts
Fixes https://github.com/penumbra-zone/dex-explorer/issues/333
Confirmed that it matches now:
=> Fix inspect timeline tx id

src/widgets/header/ui/banner.tsx
=> alpha banner

src/shared/api/middleware.ts
slight follow-up to https://github.com/penumbra-zone/dex-explorer/pull/346
=> routing: more idiomatic url path

src/pages/trade/api/book.ts, src/pages/trade/model/useMarketPrice.ts
fixes the calculation of market price - takes it from the routebook instead of the summary.
=> fix: use correct market price in liquidity provision

src/pages/trade/ui/form-tabs.tsx
=> change 'Range Liquidity' to 'Provide Liquidity'

app/inspect/block/[height]/page.tsx, app/inspect/tx/[hash]/page.tsx, src/pages/inspect/block/index.tsx, src/pages/inspect/tx/index.tsx, src/pages/inspect/ui/search.tsx
Implements https://github.com/penumbra-zone/dex-explorer/issues/351
=> Detect Inspect Input in Search

src/pages/trade/ui/positions/positions-current-value.tsx
=> Handle infinite values being returned without a runtime error

src/shared/api/server/book/index.ts
This makes the linter happy again.
=> bug: remove unnecessary console.logs

src/shared/api/server/summary/pairs.ts, src/shared/database/index.ts
Closes #335 
Uses 24 volume just like in the explore page. It is also a more performant version than what we had before
=> fix: #335: show volume instead of liquidity in pair selector

src/features/connect/connect-button.tsx, src/pages/portfolio/ui/onboarding.tsx, src/widgets/header/ui/header.tsx, src/widgets/header/ui/help-popover.tsx
Implements Phase 1 of the onboarding guide (https://github.com/penumbra-zone/dex-explorer/issues/387)
=> Portfolio onboarding phase1

src/pages/portfolio/ui/onboarding.tsx
=> fix: revert to onboarding v1
